version: '3.7'

services:
  # mongo:
  #   image: mongo:latest
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
  #   restart: always
  #   ports:
  #     - "27017:27017"

  metaslot:
    container_name: metaslot
    image: metaslot:0.0.1
    command: ["pnpm", "run", "--filter", "./frontend", "start"]
    ports:
      - "8000:3000"
    restart: always

  # mongo-express:
  #   image: mongo-express:latest
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongo
  #     - ME_CONFIG_MONGODB_PORT=27017
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  #     - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
  #     - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
  #     - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
  #     - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
  #     - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "8080:8081"
  #   restart: always
